name: "EPIC"
description: Create a new Epic issue to collect smaller issues that are part of a larger feature or goal.
title: "<title>"
labels: ["Type: epic"]
body:
    - type: textarea
      id: description
      attributes:
          label: "Description"
          description: Please enter an explicit description of the large feature or goal
          placeholder: Short and explicit description of the epic issue...
      validations:
          required: true
    - type: textarea
      id: issues
      attributes:
          label: "Sub issues"
          description: List all sub issues belonging to this
          value: |
              - [ ]
              - [ ]
              - [ ]
              ...
      validations:
          required: false