function extend_model(m::Model)
    # add_variable_node_pressure!(m)
    # add_variable_node_voltage_angle!(m)
    # add_constraint_fix_node_pressure_point!(m)
    # add_constraint_compression_ratio!(m)
    # add_constraint_storage_line_pack!(m)
    # add_constraint_init_stor_state!(m)
    # add_constraint_connection_flow_gas_capacity!(m)
    # add_constraint_node_voltage_angle_ref!(m)
    # add_constraint_node_voltage_angle!(m)
end
