# GitHub Action

name: CI

# Run workflow on every push and pull request to master branch
on:
  push:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  check_duplicate_actions:
    runs-on: ubuntu-latest
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@v5
        with:
          concurrent_skipping: "same_content_newer"
  test:
    needs: check_duplicate_actions
    if: needs.check_duplicate_actions.outputs.should_skip != 'true'
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - "1.10" # Replace "lts" with a specific Julia version
          - "1" # Latest Release of Julia v1.x
        os:
          - ubuntu-latest
          - windows-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.11"
      - uses: julia-actions/setup-julia@v3
        with:
          version: ${{ matrix.version }}
          arch: x64
      - run: |
          git config --global user.name Tester
          git config --global user.email te@st.er
      - name: Install spinedb_api
        run: julia ./.install_spinedb_api.jl
        env:
          PYTHON: python
      - name: Checkout SpineInterface
        uses: actions/checkout@v7
        with:
          repository: spine-tools/SpineInterface.jl
          path: SpineInterface.jl
      - name: Setup SpineInterface
        run: |
          julia --project=. --eval "using Pkg; Pkg.develop(path=\"SpineInterface.jl\");"
          julia --project=test --eval "using Pkg; Pkg.develop(path=\"SpineInterface.jl\");"
          julia --project=benchmark --eval "using Pkg; Pkg.develop([PackageSpec(path=\"SpineInterface.jl\"), PackageSpec(path=\".\")]);"
        shell: bash
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@latest
      - uses: julia-actions/julia-processcoverage@v1
        if: matrix.version == '1' && matrix.os == 'ubuntu-latest'
      - uses: codecov/codecov-action@v6
        with:
          files: lcov.info
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
  Documenter:
    if: github.event_name == 'pull_request' || github.ref == 'refs/heads/master'
    name: Documentation
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      - uses: actions/setup-python@v7
        with:
          python-version: "3.11"
      - name: Checkout SpineInterface
        uses: actions/checkout@v7
        with:
          repository: spine-tools/SpineInterface.jl
          path: SpineInterface.jl
      - name: Setup Julia projects
        run: |
          julia --project=. --eval "import Pkg; Pkg.develop(path=\"SpineInterface.jl\");"
          julia --project=docs --eval "import Pkg; Pkg.develop(path=\".\");"
        shell: bash
      - name: Install dependencies
        run: |
          julia ./.install_spinedb_api.jl
      - uses: julia-actions/julia-docdeploy@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
